# Generated by Django 4.2.3 on 2023-08-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("contacts", "0001_initial"),
        ("contacts", "0002_alter_contact_phone_number"),
        ("contacts", "0003_alter_contact_phone_number"),
        ("contacts", "0004_alter_contact_options"),
        ("contacts", "0005_alter_contact_phone_number"),
        ("contacts", "0006_alter_contact_phone_number"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-modified_at", "name"],
            },
        ),
    ]
