# Generated by Django 4.2.3 on 2023-08-05 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-modified_at", "name"]},
        ),
    ]
