# Generated by Django 4.2.3 on 2023-08-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
