# Generated by Django 4.2.4 on 2023-08-14 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0007_group_contact_groups"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Group_of_contact",
        ),
    ]
