# Generated by Django 4.2.4 on 2023-08-15 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0008_rename_group_group_of_contact"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group_of_contact",
            new_name="GroupOfContact",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="groups",
            new_name="groups_of_contact",
        ),
    ]
