# Generated by Django 4.2.4 on 2023-08-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0011_typeofcontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoOfContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_of_contacts",
                        to="contacts.typeofcontact",
                    ),
                ),
            ],
        ),
    ]
