# Generated by Django 4.2.4 on 2023-08-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0012_infoofcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="info_of_contact",
            field=models.ManyToManyField(related_name="contacts", to="contacts.infoofcontact"),
        ),
    ]
