# Generated by Django 4.2.4 on 2023-08-15 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0014_remove_contact_info_of_contact_infoofcontact_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infoofcontact",
            name="contact",
        ),
    ]
