# Generated by Django 4.2.4 on 2023-08-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0015_remove_infoofcontact_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="info_of_contacts",
            field=models.ManyToManyField(related_name="contacts", to="contacts.infoofcontact"),
        ),
    ]
