# Generated by Django 4.2.4 on 2023-08-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0016_contact_info_of_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infoofcontact",
            name="type",
        ),
        migrations.AddField(
            model_name="infoofcontact",
            name="type",
            field=models.ManyToManyField(related_name="info_of_contacts", to="contacts.typeofcontact"),
        ),
    ]
