# Generated by Django 4.2.4 on 2023-08-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0017_remove_infoofcontact_type_infoofcontact_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infoofcontact",
            name="type",
        ),
        migrations.AddField(
            model_name="infoofcontact",
            name="type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info_of_contacts",
                to="contacts.typeofcontact",
            ),
            preserve_default=False,
        ),
    ]
