# Generated by Django 4.2.4 on 2023-08-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0019_remove_contact_info_of_contacts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="info_of_contact",
            field=models.ManyToManyField(related_name="contacts", to="contacts.infoofcontact"),
        ),
    ]
