# Generated by Django 4.2.4 on 2023-08-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0020_contact_info_of_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infoofcontact",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="info_of_contact",
        ),
        migrations.AddField(
            model_name="contact",
            name="info_of_contact",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to="contacts.infoofcontact",
            ),
            preserve_default=False,
        ),
    ]
