# Generated by Django 4.2.4 on 2023-08-15 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0021_remove_infoofcontact_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="phone_number",
        ),
    ]
