# Generated by Django 4.2.4 on 2023-08-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0022_remove_contact_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="info_of_contact",
        ),
        migrations.AddField(
            model_name="infoofcontact",
            name="contact",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info_list_of_contact",
                to="contacts.contact",
            ),
            preserve_default=False,
        ),
    ]
