# Generated by Django 4.2.4 on 2023-08-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0023_remove_contact_info_of_contact_infoofcontact_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="info_of_contact",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="contacts.infoofcontact",
            ),
            preserve_default=False,
        ),
    ]
