# Generated by Django 4.2.4 on 2023-08-15 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0024_contact_info_of_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="info_of_contact",
        ),
    ]
