# Generated by Django 4.2.6 on 2023-10-13 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"ordering": ["-updated_at", "-created_at", "url"]},
        ),
        migrations.AlterModelOptions(
            name="subsite",
            options={"ordering": ["-updated_at", "-created_at", "site"]},
        ),
    ]
