# Generated by Django 4.2.6 on 2023-10-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0003_alter_subsite_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsite",
            name="flag_was_finished_crawling",
            field=models.BooleanField(default=False),
        ),
    ]
